project:
  type: website
  output-dir: docs
website:
  title: ""
  navbar:
    theme: solar
    left:
      - href: index.qmd
        text: ПыПецПром
      - resources.qmd
      - Factories.qmd

format:
  html:
    theme:
      - solar
    css: styles.css
    toc: true



